name: Android APK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm test

  build-android:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-34 build-tools;34.0.0 platform-tools'
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses
      - name: Prebuild Android (Expo -> Native)
        env:
          CI: '1'
          EXPO_PUBLIC_MAPTILER_KEY: ${{ secrets.EXPO_PUBLIC_MAPTILER_KEY }}
        run: npx expo prebuild -p android --no-install --clean
      - name: Ensure Maven Central and Google repos for all projects
        working-directory: android
        run: |
          cat > repos.init.gradle << 'EOF'
          allprojects { project ->
            repositories {
              mavenCentral()
              google()
            }
          }
          EOF
      - name: Build APK (release unsigned)
        working-directory: android
        run: ./gradlew -I repos.init.gradle assembleRelease --stacktrace
      - name: Build APK (debug)
        working-directory: android
        run: ./gradlew -I repos.init.gradle assembleDebug --stacktrace
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            android/app/build/outputs/apk/release/*.apk
            android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
